# Generated by Django 2.1.3 on 2018-11-28 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.IntegerField(max_length=12)),
                ('posture', models.FloatField(default=0)),
                ('saX', models.FloatField(default=0)),
                ('saY', models.FloatField(default=0)),
                ('saZ', models.FloatField(default=0)),
                ('sgX', models.FloatField(default=0)),
                ('sgY', models.FloatField(default=0)),
                ('sgZ', models.FloatField(default=0)),
                ('xdegree', models.FloatField(default=0)),
                ('ydegree', models.FloatField(default=0)),
                ('zdegree', models.FloatField(default=0)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-date',),
            },
        ),
        migrations.CreateModel(
            name='Posture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=10)),
                ('date', models.CharField(max_length=10, unique=True)),
                ('bad_count', models.IntegerField(default=0)),
                ('all_count', models.IntegerField(default=0)),
                ('ratio', models.FloatField(default=0)),
            ],
            options={
                'ordering': ('-date',),
            },
        ),
    ]
