# Generated by Django 2.1.3 on 2018-11-09 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=10)),
                ('acX', models.FloatField(default=0)),
                ('acY', models.FloatField(default=0)),
                ('acZ', models.FloatField(default=0)),
                ('gyX', models.FloatField(default=0)),
                ('gyY', models.FloatField(default=0)),
                ('gyZ', models.FloatField(default=0)),
                ('aXR', models.FloatField(default=0)),
                ('aYR', models.FloatField(default=0)),
                ('submit_datetime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
