# Generated by Django 2.1.3 on 2018-11-26 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
            ],
            options={
                'ordering': ('device',),
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=10)),
                ('posture', models.IntegerField(default=0)),
                ('saX', models.FloatField(default=0)),
                ('saY', models.FloatField(default=0)),
                ('saZ', models.FloatField(default=0)),
                ('sgX', models.FloatField(default=0)),
                ('sgY', models.FloatField(default=0)),
                ('sgZ', models.FloatField(default=0)),
                ('xdegree', models.FloatField(default=0)),
                ('ydegree', models.FloatField(default=0)),
                ('zdegree', models.FloatField(default=0)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('date',),
            },
        ),
        migrations.CreateModel(
            name='Init',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=10)),
                ('saX', models.FloatField(default=0)),
                ('saY', models.FloatField(default=0)),
                ('saZ', models.FloatField(default=0)),
                ('sgX', models.FloatField(default=0)),
                ('sgY', models.FloatField(default=0)),
                ('sgZ', models.FloatField(default=0)),
                ('xdegree', models.FloatField(default=0)),
                ('ydegree', models.FloatField(default=0)),
                ('zdegree', models.FloatField(default=0)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('date',),
            },
        ),
        migrations.CreateModel(
            name='Sync',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=10)),
                ('syn_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('device_id',),
            },
        ),
        migrations.AddField(
            model_name='analysis',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='posture.Device'),
        ),
    ]
