# Generated by Django 2.1.3 on 2018-11-28 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posture', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=10)),
                ('date', models.DateTimeField(auto_now=True)),
                ('bad_count', models.IntegerField(default=0)),
                ('all_count', models.IntegerField(default=0)),
                ('ratio', models.FloatField(default=0)),
            ],
            options={
                'ordering': ('-date',),
            },
        ),
        migrations.RemoveField(
            model_name='analysis',
            name='device',
        ),
        migrations.DeleteModel(
            name='Init',
        ),
        migrations.DeleteModel(
            name='Sync',
        ),
        migrations.AlterModelOptions(
            name='device',
            options={'ordering': ('-date',)},
        ),
        migrations.DeleteModel(
            name='Analysis',
        ),
    ]
