# Generated by Django 2.1.3 on 2018-11-09 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posture', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='submit_datetime',
            new_name='time',
        ),
        migrations.RemoveField(
            model_name='device',
            name='aXR',
        ),
        migrations.RemoveField(
            model_name='device',
            name='aYR',
        ),
        migrations.RemoveField(
            model_name='device',
            name='acX',
        ),
        migrations.RemoveField(
            model_name='device',
            name='acY',
        ),
        migrations.RemoveField(
            model_name='device',
            name='acZ',
        ),
        migrations.RemoveField(
            model_name='device',
            name='gyX',
        ),
        migrations.RemoveField(
            model_name='device',
            name='gyY',
        ),
        migrations.RemoveField(
            model_name='device',
            name='gyZ',
        ),
        migrations.AddField(
            model_name='device',
            name='saX',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='saY',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='saZ',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='sgX',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='sgY',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='sgZ',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='xdegree',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='ydegree',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='zdegree',
            field=models.FloatField(default=0, null=True),
        ),
    ]
