# Generated by Django 2.1.3 on 2018-11-13 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posture', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snippet',
            name='highlighted',
        ),
        migrations.RemoveField(
            model_name='snippet',
            name='owner',
        ),
        migrations.AlterField(
            model_name='device',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
