# Generated by Django 2.1.3 on 2018-11-28 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posture', '0002_auto_20181128_0344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posture',
            name='date',
            field=models.CharField(max_length=10),
        ),
    ]
