# Generated by Django 2.1.3 on 2018-11-09 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posture', '0002_auto_20181109_2345'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='device',
            options={'ordering': ('time',)},
        ),
    ]
