# Generated by Django 2.1.3 on 2018-11-13 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posture', '0002_auto_20181113_2117'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='device',
            options={'ordering': ('datetime',)},
        ),
        migrations.RenameField(
            model_name='device',
            old_name='time',
            new_name='datetime',
        ),
    ]
