# Generated by Django 2.1.3 on 2018-11-14 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posture', '0004_auto_20181113_2148'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Snippet',
        ),
    ]
