# Generated by Django 2.1.3 on 2018-11-15 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posture', '0005_delete_snippet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='posturedata',
            name='end_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='posturedata',
            name='start_date',
            field=models.DateTimeField(),
        ),
    ]
