# Generated by Django 2.1.3 on 2018-11-09 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posture', '0006_auto_20181110_0039'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='posture',
            field=models.IntegerField(default=0),
        ),
    ]
