# Generated by Django 2.1.3 on 2018-11-11 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posture', '0008_auto_20181110_0046'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostureData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
            options={
                'ordering': ('device_id',),
            },
        ),
        migrations.AlterField(
            model_name='device',
            name='time',
            field=models.DateTimeField(),
        ),
        migrations.AddField(
            model_name='posturedata',
            name='device_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='posture.Device'),
        ),
    ]
