# Generated by Django 2.1.3 on 2018-11-11 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posture', '0009_auto_20181112_0104'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='posturedata',
            options={'ordering': ('device',)},
        ),
        migrations.RenameField(
            model_name='posturedata',
            old_name='device_id',
            new_name='device',
        ),
    ]
